import { NextRequest, NextResponse } from "next/server";

// Content negotiation for AI agents: clients that explicitly ask for
// `Accept: text/markdown` on a docs page get the raw-markdown mirror
// generated by scripts/generate-full-docs.js (same content the `.md` URL
// suffix serves). Browsers never send text/markdown, so human traffic is
// unaffected. `Vary: Accept` keeps CDN caches from mixing the two.
export function middleware(req: NextRequest) {
  const { pathname } = req.nextUrl;
  const accept = req.headers.get("accept") || "";

  const isPageRoute =
    !pathname.startsWith("/_next") &&
    !pathname.startsWith("/api") &&
    !/\.[a-zA-Z0-9]+$/.test(pathname);

  if (isPageRoute && accept.includes("text/markdown")) {
    const url = req.nextUrl.clone();
    url.pathname = pathname === "/" ? "/index.md" : `${pathname.replace(/\/$/, "")}.md`;
    const res = NextResponse.rewrite(url);
    res.headers.set("Vary", "Accept");
    return res;
  }

  const res = NextResponse.next();
  if (isPageRoute) {
    res.headers.set("Vary", "Accept");
  }
  return res;
}
