import React from "react";
import { DocsThemeConfig, useConfig } from "nextra-theme-docs";
import { useRouter } from "next/router";
import TelegramIcon from "./components/icons/telegram";
import Logo from "./components/icon";
import TwitterLogo from "./components/icons/twitter";
import DiscordIcon from "./components/icons/discord";
import GitHubIcon from "./components/icons/github";
import CopyPage from "./components/copy-page";

const SITE_URL = "https://docs.genlayer.com";
const DEFAULT_DESCRIPTION =
  "Documentation for GenLayer, the adjudication layer for the agentic economy. Build Intelligent Contracts in Python, integrate the SDKs, and run a validator node.";

// Path of the raw-markdown mirror generated by scripts/generate-full-docs.js
function markdownPathFor(asPath: string): string {
  const cleanPath = asPath.split(/[?#]/)[0].replace(/\/$/, "");
  return cleanPath === "" ? "/index.md" : `${cleanPath}.md`;
}

function segmentToTitle(segment: string): string {
  return segment
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}

const config: DocsThemeConfig = {
  logo: <Logo />,
  docsRepositoryBase: "https://github.com/genlayerlabs/genlayer-docs/tree/main",
  footer: {
    text: "GenLayer Documentation",
  },
  sidebar: {
    defaultMenuCollapseLevel: 1,
  },
  navigation: true,
  head: function Head() {
    const { asPath } = useRouter();
    const { frontMatter, title } = useConfig();
    const cleanPath = asPath.split(/[?#]/)[0];
    const url = `${SITE_URL}${cleanPath === "/" ? "" : cleanPath.replace(/\/$/, "")}`;
    const description = frontMatter.description || DEFAULT_DESCRIPTION;

    const segments = cleanPath.split("/").filter(Boolean);
    const breadcrumbList = {
      "@context": "https://schema.org",
      "@type": "BreadcrumbList",
      itemListElement: [
        { "@type": "ListItem", position: 1, name: "GenLayer Documentation", item: SITE_URL },
        ...segments.map((segment, i) => ({
          "@type": "ListItem",
          position: i + 2,
          name: segmentToTitle(segment),
          item: `${SITE_URL}/${segments.slice(0, i + 1).join("/")}`,
        })),
      ],
    };
    const techArticle = {
      "@context": "https://schema.org",
      "@type": "TechArticle",
      headline: title || "GenLayer Documentation",
      description,
      url,
      publisher: {
        "@type": "Organization",
        name: "GenLayer",
        url: "https://www.genlayer.com",
        logo: `${SITE_URL}/assets/genlayer.png`,
      },
    };

    return (
      <>
        <link rel="icon" href="/favicon.png" type="image/png" media="(prefers-color-scheme: light)" />
        <link rel="icon" href="/favicon-dark.png" type="image/png" media="(prefers-color-scheme: dark)" />
        <link
          rel="alternate"
          type="text/markdown"
          href={markdownPathFor(asPath)}
          title="Markdown version of this page"
        />
        <link rel="canonical" href={url} />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify([techArticle, breadcrumbList]).replace(/</g, "\\u003c"),
          }}
        />
      </>
    );
  },
  navbar: {
    extraContent: (
      <div style={{ display: "flex", alignItems: "center" }}>
        <CopyPage />
        <a href="https://github.com/genlayerlabs" style={{ marginRight: 10 }}>
          <GitHubIcon />
        </a>
        <a href="https://t.me/genlayer" style={{ marginRight: 10 }}>
          <TelegramIcon />
        </a>
        <a href="https://x.com/GenLayer" style={{ marginRight: 10 }}>
          <TwitterLogo />
        </a>
        <a href="https://discord.gg/8Jm4v89VAu" style={{ marginRight: 10 }}>
          <DiscordIcon />
        </a>
      </div>
    ),
  },

  useNextSeoProps: () => {
    const { asPath } = useRouter();
    const { frontMatter } = useConfig();
    const isHomePage = asPath === "/";
    const description = frontMatter.description || DEFAULT_DESCRIPTION;
    return {
      titleTemplate: isHomePage
        ? "GenLayer — The Adjudication Layer for the Agentic Economy"
        : "%s | GenLayer Documentation",
      description,
      openGraph: {
        type: "website",
        locale: "en_IE",
        url: SITE_URL + asPath,
        site_name: "GenLayer — The Adjudication Layer for the Agentic Economy",
        title: "GenLayer — The Adjudication Layer for the Agentic Economy",
        description,
        images: [
          {
            url: "/assets/genlayer.png",
            width: 150,
            height: 55,
            alt: "GenLayer Logo",
          },
        ],
      },
      additionalMetaTags: [
        {
          property: "og:image",
          content: `${SITE_URL}/assets/genlayer.png`,
        },
      ],
    };
  },
};

export default config;
