# Centralized configuration for documentation sync operations
# This replaces scattered hardcoded values throughout the workflow

repositories:
  source:
    owner: genlayerlabs
    name: genlayer-node
    sparse_checkout:
      - docs
      - configs/node/config.yaml.example

paths:
  changelog:
    source: docs/changelog
    destination: content/validators/changelog
    description: "Validator changelog files"
  
  config:
    source: configs/node/config.yaml.example
    destination: content/validators/config.yaml
    description: "Node configuration template"
  
  api_gen:
    source: docs/api/rpc
    destination: pages/api-references/genlayer-node/gen
    description: "GenLayer API method documentation"
  
  api_debug:
    source: docs/api/rpc
    destination: pages/api-references/genlayer-node/debug
    description: "Debug API method documentation"

filters:
  api_gen_regex: 'gen_(?!dbg_).*'
  api_debug_regex: 'gen_dbg_.*'

scripts:
  post_sync:
    - name: "Generate changelog"
      command: "npm run node-generate-changelog"
      description: "Process and generate changelog documentation"
    
    - name: "Update setup guide"
      command: "npm run node-update-setup-guide"
      description: "Update version references in setup guide"
    
    - name: "Update config in setup guide"
      command: "npm run node-update-config"
      description: "Update configuration in setup guide"
    
    - name: "Generate API docs"
      command: "npm run node-generate-api-docs"
      description: "Generate API documentation from individual method files"

defaults:
  version: "latest"
  changelog_path: "docs/changelog"
  api_gen_path: "docs/api/rpc"
  api_debug_path: "docs/api/rpc"
  
git:
  branch_prefix: "docs/node/"
  commit_message_template: |
    docs: Sync documentation from node repository {version}
    
    - Source: genlayerlabs/genlayer-node@{version}
    - Version: {version}
    - Total changes: {total_changes}
    - Added: {total_added} files
    - Updated: {total_updated} files
    - Deleted: {total_deleted} files

pr:
  title_template: "docs: Sync documentation from genlayer-node {version}"
  labels:
    - "documentation"
    - "node"
  base_branch: "main"