name: 'Sync Files'
description: 'Generic file synchronization with regex filtering - eliminates code duplication'
inputs:
  sync_type:
    description: 'Type of sync operation (changelog, config, api_gen, api_debug)'
    required: true
  version:
    description: 'Version being synced'
    required: true
  changelog_path:
    description: 'Path to changelog files in source repo'
    required: false
    default: 'docs/changelog'
  api_gen_path:
    description: 'Path to API gen files in source repo'  
    required: false
    default: 'docs/api/rpc'
  api_debug_path:
    description: 'Path to API debug files in source repo'
    required: false
    default: 'docs/api/rpc'
  api_gen_regex:
    description: 'Regex pattern to filter API gen files'
    required: false
    default: 'gen_(?!dbg_).*'
  api_debug_regex:
    description: 'Regex pattern to filter API debug files'
    required: false
    default: 'gen_dbg_.*'
  api_ops_path:
    description: 'Path to API ops files in source repo'
    required: false
    default: 'docs/api/ops'
outputs:
  files_added:
    description: 'Number of files added'
    value: ${{ steps.sync.outputs.added }}
  files_updated:
    description: 'Number of files updated'
    value: ${{ steps.sync.outputs.updated }}
  files_deleted:
    description: 'Number of files deleted'
    value: ${{ steps.sync.outputs.deleted }}
  total_changes:
    description: 'Total number of changes'
    value: ${{ steps.sync.outputs.total }}
runs:
  using: 'composite'
  steps:
    - name: Sync files using script
      id: sync
      shell: bash
      run: |
        .github/scripts/sync-files.sh \
          "${{ inputs.sync_type }}" \
          "${{ inputs.version }}" \
          "${{ inputs.changelog_path }}" \
          "${{ inputs.api_gen_path }}" \
          "${{ inputs.api_debug_path }}" \
          "${{ inputs.api_ops_path }}" \
          "${{ inputs.api_gen_regex }}" \
          "${{ inputs.api_debug_regex }}"