#!/usr/bin/env node
/**
 * Content retrofit driver: uses Codex CLI to add answer-first frontmatter
 * descriptions and answer-first intro paragraphs to docs pages, with two
 * verification layers before any change is written:
 *
 *   1. Mechanical (this script): Codex only returns {description, intro};
 *      everything from the first H2 onward must remain byte-identical, the
 *      H1 must be unchanged, code fences and links in the intro preserved,
 *      and the description must be 50-170 chars on one line.
 *   2. LLM verifier: a second, independent `codex exec` call judges the
 *      revision for factual fidelity and terminology before it is accepted.
 *
 * Codex runs with --sandbox read-only so it can read the repo for context
 * (neighboring pages, llms.txt) but can never write; this script is the
 * only writer.
 *
 * Usage:
 *   node scripts/retrofit/retrofit.js --list             # show targets
 *   node scripts/retrofit/retrofit.js --limit 3          # pilot run
 *   node scripts/retrofit/retrofit.js                    # full run
 *   node scripts/retrofit/retrofit.js pages/foo.mdx ...  # specific pages
 *   Flags: --concurrency N (default 3), --dry-run (don't write files)
 */
const fs = require('fs');
const path = require('path');
const os = require('os');
const { execFile } = require('child_process');

const REPO = process.cwd();
const PAGES_DIR = path.join(REPO, 'pages');
const SCHEMA_REVISION = path.join(__dirname, 'schema-revision.json');
const SCHEMA_VERDICT = path.join(__dirname, 'schema-verdict.json');
const LOG_PATH = path.join(__dirname, 'retrofit-log.json');
const CODEX_TIMEOUT_MS = 8 * 60 * 1000;

// Paths owned by generators or external sync jobs — never retrofit these.
const EXCLUDED_PREFIXES = [
  'api-references/genlayer-cli/', // synced from the genlayer-cli repo
  'api-references/genlayer-node/', // generated by generate-api-docs.js
];
const EXCLUDED_FILES = [
  'api-references/genlayer-cli.mdx', // synced
  'api-references/genlayer-node.mdx', // generated
  'validators/changelog.mdx', // generated by generate-changelog.js
];

const CANON = `Project context — GenLayer documentation (docs.genlayer.com):
GenLayer is the first Intelligent Blockchain: an L2 (on zkSync Elastic Chain, anchored to Ethereum) whose smart contracts — called Intelligent Contracts, written in Python — can natively access the web, call LLMs, and reach consensus on non-deterministic, subjective outcomes. Consensus mechanism: Optimistic Democracy; validators agree on non-deterministic outputs via the Equivalence Principle. Execution environment: GenVM. Dev tools: GenLayer CLI, GenLayer Studio (browser IDE), GenLayerJS / GenLayerPY SDKs, GenLayer Testing Suite (genlayer-test). Networks: Localnet, Studionet, Testnet Asimov.

Canonical terminology — always use exactly these names: "Intelligent Contract" (never "AI contract" or "smart contract 2.0"), "Optimistic Democracy", "Equivalence Principle", "GenVM", "GenLayer Studio". You may read other files in this repository (e.g. public/llms.txt, sibling pages in the same directory) to stay consistent with how concepts are described elsewhere.`;

function listTargets() {
  const targets = [];
  (function walk(dir) {
    for (const entry of fs.readdirSync(dir).sort()) {
      if (entry.startsWith('_') || entry.startsWith('.')) continue;
      const full = path.join(dir, entry);
      if (fs.statSync(full).isDirectory()) {
        walk(full);
        continue;
      }
      if (!entry.endsWith('.mdx')) continue; // .md files are synced API refs
      const rel = path.relative(PAGES_DIR, full).split(path.sep).join('/');
      if (EXCLUDED_PREFIXES.some((p) => rel.startsWith(p))) continue;
      if (EXCLUDED_FILES.includes(rel)) continue;
      const raw = fs.readFileSync(full, 'utf8');
      if (raw.length < 300 && /This page has moved/i.test(raw)) continue; // SEO stubs
      if (/^---\n[\s\S]*?\bdescription:/.test(raw)) continue; // already done
      targets.push(full);
    }
  })(PAGES_DIR);
  return targets;
}

// Split a page into { frontmatter, h1Line, intro, tail }.
// intro = content between the H1 line and the first H2 (or '' if H1 is
// immediately followed by an H2 / there is no H1). tail = everything else,
// which must remain byte-identical after the retrofit.
function splitPage(raw) {
  let frontmatter = '';
  let body = raw;
  const fm = raw.match(/^---\n[\s\S]*?\n---\n/);
  if (fm) {
    frontmatter = fm[0];
    body = raw.slice(fm[0].length);
  }
  const lines = body.split('\n');
  const h1Index = lines.findIndex((l) => /^#\s/.test(l));
  if (h1Index === -1) return null; // no H1 — handled elsewhere, skip
  let end = lines.length;
  let inFence = false;
  for (let i = h1Index + 1; i < lines.length; i++) {
    if (/^(```|~~~)/.test(lines[i])) inFence = !inFence;
    if (!inFence && /^##\s/.test(lines[i])) {
      end = i;
      break;
    }
  }
  return {
    frontmatter,
    preH1: lines.slice(0, h1Index).join('\n'),
    h1Line: lines[h1Index],
    intro: lines.slice(h1Index, end).join('\n'),
    tail: lines.slice(end).join('\n'),
  };
}

function extract(regex, text) {
  return (text.match(regex) || []).join('\n');
}

function mechanicalCheck(page, result) {
  const issues = [];
  const { description, intro } = result;
  if (typeof description !== 'string' || typeof intro !== 'string') {
    return ['codex did not return description/intro strings'];
  }
  if (description.length < 50 || description.length > 170) {
    issues.push(`description length ${description.length} outside 50-170`);
  }
  if (/\n/.test(description)) issues.push('description contains newline');
  const newH1 = intro.split('\n')[0];
  if (newH1.trim() !== page.h1Line.trim()) {
    issues.push(`H1 changed: "${page.h1Line}" -> "${newH1}"`);
  }
  if (/^##\s/m.test(intro)) issues.push('intro contains an H2 — it would swallow the next section');
  const fences = /```[\s\S]*?```/g;
  if (extract(fences, intro) !== extract(fences, page.intro)) {
    issues.push('code fences in intro were modified');
  }
  const links = /\]\(([^)]+)\)/g;
  const oldLinks = page.intro.match(links) || [];
  const newLinks = new Set(intro.match(links) || []);
  for (const link of oldLinks) {
    if (!newLinks.has(link)) issues.push(`link removed from intro: ${link}`);
  }
  // Sanity bound: an answer-first rewrite should not balloon the intro
  if (intro.length > Math.max(page.intro.length * 2, page.intro.length + 800)) {
    issues.push('intro grew implausibly large');
  }
  return issues;
}

function runCodex(prompt, schemaPath) {
  return new Promise((resolve, reject) => {
    const outFile = path.join(
      os.tmpdir(),
      `codex-out-${Date.now()}-${Math.random().toString(36).slice(2)}.json`
    );
    const child = execFile(
      'codex',
      [
        'exec',
        '--sandbox', 'read-only',
        '--ephemeral',
        '--color', 'never',
        '--output-schema', schemaPath,
        '-o', outFile,
        '-C', REPO,
        '-', // prompt via stdin (avoids argv length limits)
      ],
      { timeout: CODEX_TIMEOUT_MS, maxBuffer: 16 * 1024 * 1024 },
      (error, stdout, stderr) => {
        try {
          if (fs.existsSync(outFile)) {
            const out = fs.readFileSync(outFile, 'utf8');
            fs.unlinkSync(outFile);
            return resolve(JSON.parse(out));
          }
        } catch (parseError) {
          return reject(new Error(`unparseable codex output: ${parseError.message}`));
        }
        reject(new Error(`codex exec failed: ${error ? error.message : 'no output'}\n${stderr?.slice(-500)}`));
      }
    );
    child.stdin.write(prompt);
    child.stdin.end();
  });
}

async function retrofitPage(file, opts) {
  const rel = path.relative(REPO, file).split(path.sep).join('/');
  const raw = fs.readFileSync(file, 'utf8');
  const page = splitPage(raw);
  if (!page) return { file: rel, status: 'skipped', reason: 'no H1' };

  const revisionPrompt = `${CANON}

Task: improve ONE documentation page for retrieval by LLMs and answer engines. File: ${rel}

You may ONLY produce two things (returned via the output schema — do not write any files):
1. "description": an answer-first meta description of this page, 50-160 characters, one line, no quotes-escaping issues. It must directly state what the page covers, leading with the topic entity.
2. "intro": a revised version of the intro region shown below (the H1 line plus everything before the first H2). Requirements:
   - Keep the H1 line EXACTLY as it is.
   - The first paragraph must be answer-first: define the topic/term in the first sentence so the section is comprehensible if extracted alone. Avoid starting with context-dependent pronouns ("It", "This").
   - Preserve every fact, link, code block, and component tag that exists in the current intro. You may reorder and rephrase prose; do not invent new facts or capabilities.
   - If the intro is empty (H1 immediately followed by H2), write a single new 1-3 sentence answer-first paragraph summarizing the page from its content below.
   - Keep MDX components (e.g. <Callout>) untouched if present.

Current intro region:
<intro>
${page.intro}
</intro>

Rest of the page (READ-ONLY — for context; you cannot change it):
<rest>
${page.tail.slice(0, 6000)}
</rest>`;

  let revision;
  try {
    revision = await runCodex(revisionPrompt, SCHEMA_REVISION);
  } catch (error) {
    return { file: rel, status: 'error', reason: error.message };
  }

  const mechanical = mechanicalCheck(page, revision);
  if (mechanical.length) {
    return { file: rel, status: 'rejected-mechanical', reason: mechanical.join('; ') };
  }

  const verdictPrompt = `${CANON}

You are reviewing a proposed documentation edit for the page ${rel}. Approve it ONLY if:
- Every factual claim in the revised intro is supported by the original intro or the rest of the page (no invented capabilities, numbers, or names).
- Canonical GenLayer terminology is used correctly.
- The new text reads as documentation, not marketing, and the proposed meta description accurately summarizes the page.
You may read the full page in the repository at ${rel} for context.

ORIGINAL intro:
<original>
${page.intro}
</original>

REVISED intro:
<revised>
${revision.intro}
</revised>

Proposed meta description: ${revision.description}`;

  let verdict;
  try {
    verdict = await runCodex(verdictPrompt, SCHEMA_VERDICT);
  } catch (error) {
    return { file: rel, status: 'error', reason: `verifier: ${error.message}` };
  }
  if (!verdict.approved) {
    return { file: rel, status: 'rejected-verifier', reason: (verdict.issues || []).join('; ') };
  }

  const description = revision.description.replace(/"/g, "'").trim();
  let frontmatter = page.frontmatter;
  if (frontmatter) {
    frontmatter = frontmatter.replace(/\n---\n$/, `\ndescription: "${description}"\n---\n`);
  } else {
    frontmatter = `---\ndescription: "${description}"\n---\n`;
  }
  const preH1 = page.preH1 ? `${page.preH1}\n` : '\n';
  const intro = revision.intro.replace(/\s+$/, '');
  const updated = `${frontmatter}${preH1}${intro}\n\n${page.tail}`;

  if (!opts.dryRun) fs.writeFileSync(file, updated);
  return { file: rel, status: 'applied', description, notes: revision.notes };
}

async function main() {
  const args = process.argv.slice(2);
  const opts = {
    dryRun: args.includes('--dry-run'),
    list: args.includes('--list'),
    limit: args.includes('--limit') ? parseInt(args[args.indexOf('--limit') + 1], 10) : Infinity,
    concurrency: args.includes('--concurrency')
      ? parseInt(args[args.indexOf('--concurrency') + 1], 10)
      : 3,
  };
  const explicit = args.filter((a) => a.endsWith('.mdx')).map((a) => path.resolve(a));
  let targets = explicit.length ? explicit : listTargets();
  if (opts.list) {
    targets.forEach((t) => console.log(path.relative(REPO, t)));
    console.log(`\n${targets.length} target pages`);
    return;
  }
  targets = targets.slice(0, opts.limit);
  console.log(`retrofit: ${targets.length} pages, concurrency ${opts.concurrency}${opts.dryRun ? ' (dry run)' : ''}`);

  const results = [];
  let next = 0;
  async function worker() {
    while (next < targets.length) {
      const file = targets[next++];
      const rel = path.relative(REPO, file);
      process.stdout.write(`→ ${rel}\n`);
      const result = await retrofitPage(file, opts);
      results.push(result);
      process.stdout.write(`  ${result.status}${result.reason ? `: ${result.reason.slice(0, 160)}` : ''}\n`);
    }
  }
  await Promise.all(Array.from({ length: opts.concurrency }, worker));

  const byStatus = {};
  for (const r of results) byStatus[r.status] = (byStatus[r.status] || 0) + 1;
  console.log('\nSummary:', JSON.stringify(byStatus));
  fs.writeFileSync(LOG_PATH, JSON.stringify(results, null, 2));
  console.log(`Log: ${path.relative(REPO, LOG_PATH)}`);
  if (!opts.dryRun && byStatus.applied) {
    console.log('\nNext: review `git diff`, then run:');
    console.log('  node scripts/generate-full-docs.js && node scripts/check-llm-exports.js && npx next build');
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
